app:
  needs: [redis]
  env:
    - name: REDIS_URL
      value: redis://redis:80
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 256Mi
redis:
  enabled: true
