name: Review

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  build-app:
    name: Build & Register App
    runs-on: ubuntu-latest
    steps:
      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          imagePackage: app
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@master
        with:
          environment: "dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_Name }}
